{{- if .Values.firewall.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "meridian.service.fullname" (dict "context" . "service" "firewall") }}
  labels:
    {{- include "meridian.service.labels" (dict "context" . "service" "firewall") | nindent 4 }}
spec:
  type: {{ .Values.firewall.service.type }}
  ports:
  - port: {{ .Values.firewall.service.port }}
    targetPort: {{ .Values.firewall.service.targetPort }}
    protocol: TCP
    name: http
  selector:
    {{- include "meridian.service.selectorLabels" (dict "context" . "service" "firewall") | nindent 4 }}
{{- end }}
