{{- if .Values.console.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "meridian.service.fullname" (dict "context" . "service" "console") }}
  labels:
    {{- include "meridian.service.labels" (dict "context" . "service" "console") | nindent 4 }}
spec:
  type: {{ .Values.console.service.type }}
  {{- if .Values.console.sessionAffinity }}
  sessionAffinity: {{ .Values.console.sessionAffinity }}
  {{- end }}
  ports:
  - port: {{ .Values.console.service.port }}
    targetPort: {{ .Values.console.service.targetPort }}
    protocol: TCP
    name: http
  selector:
    {{- include "meridian.service.selectorLabels" (dict "context" . "service" "console") | nindent 4 }}
{{- end }}
